In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

with open('data_1.txt', 'r') as f:
    data = f.readlines()

column_name = data[0].strip().split()

print(column_name)

data_split = [x.strip().split() for x in data[1:]]

print(data_split[0])

['Price', 'Age_08_04', 'KM', 'HP', 'Met_Color', 'Automatic', 'CC', 'Doors', 'Quarterly_Tax', 'Weight', 'Fuel_Type_CNG', 'Fuel_Type_Diesel', 'Fuel_Type_Petrol', 'Fuel_Type']
['13500', '23', '46986', '90', '1', '0', '2000', '3', '210', '1165', '0', '1', '0', 'Diesel']


In [9]:
df = pd.DataFrame(data_split, columns = column_name)

df = df.iloc[0:5,]
df

Price Age_08_04     KM  HP Met_Color Automatic    CC Doors Quarterly_Tax  \
0  13500        23  46986  90         1         0  2000     3           210   
1  13750        23  72937  90         1         0  2000     3           210   
2  13950        24  41711  90         1         0  2000     3           210   
3  14950        26  48000  90         0         0  2000     3           210   
4  13750        30  38500  90         0         0  2000     3           210   

  Weight Fuel_Type_CNG Fuel_Type_Diesel Fuel_Type_Petrol Fuel_Type  
0   1165             0                1                0    Diesel  
1   1165             0                1                0    Diesel  
2   1165             0                1                0    Diesel  
3   1165             0                1                0    Diesel  
4   1170             0                1                0    Diesel

In [22]:
X = df[['KM', 'CC', 'HP']]
y = df['Price']

model = LinearRegression()

bootstraps = 100

preds = np.zeros(bootstraps)
means = np.zeros(bootstraps)
stds = np.zeros(bootstraps)

for i in range(bootstraps):
    sample_indices = np.random.choice(X.shape[0], size=X.shape[0], replace=False)
    
    X_sample = X.iloc[sample_indices]
    y_sample = y.iloc[sample_indices]
    model.fit(X_sample, y_sample)
    print(model.predict(X.iloc[0:4]))

[13990.26790669 13889.36573822 14010.77805808 13986.32529181]
[13990.26790669 13889.36573822 14010.77805808 13986.32529181]
[13990.26790669 13889.36573822 14010.77805808 13986.32529181]
[13990.26790669 13889.36573822 14010.77805808 13986.32529181]
[13990.26790669 13889.36573822 14010.77805808 13986.32529181]
[13990.26790669 13889.36573822 14010.77805808 13986.32529181]
[13990.26790669 13889.36573822 14010.77805808 13986.32529181]
[13990.26790669 13889.36573822 14010.77805808 13986.32529181]
[13990.26790669 13889.36573822 14010.77805808 13986.32529181]
[13990.26790669 13889.36573822 14010.77805808 13986.32529181]
[13990.26790669 13889.36573822 14010.77805808 13986.32529181]
[13990.26790669 13889.36573822 14010.77805808 13986.32529181]
[13990.26790669 13889.36573822 14010.77805808 13986.32529181]
[13990.26790669 13889.36573822 14010.77805808 13986.32529181]
[13990.26790669 13889.36573822 14010.77805808 13986.32529181]
[13990.26790669 13889.36573822 14010.77805808 13986.32529181]
[13990.2

In [7]:
X.shape[0]

1436